### ISSUE TITLE
[MarketToken] Test converted TypeScript ABI

### ISSUE THREAD

**Issue by rojosnow** [MARKETProtocol/types#2]
## Before you `start work`

Please read our contribution [guidelines](https://docs.marketprotocol.io/#contributing) and if there is a bounty involved  please also see [here](https://docs.marketprotocol.io/#gitcoin-and-bounties)

If you have ongoing work from other bounties with us where funding has not been released, please do not pick up a new issue.  We would like to involve as many contributors as possible and parallelize the work flow as much as possible.

Please make sure to comment in the issue here immediately after starting work so we know your plans for implementation and a timeline.

Please also note that in order for work to be accepted, all code must be accompanied by test cases as well.

### User Story

As a developer, I need to ensure the MARKET API TypeScript ABIs work correctly so that I can correctly interface with the MARKET contracts.

### Why Is this Needed?

*Summary*: We need to have automated test coverage for all TypeScript ABIs. This started as part of https://github.com/MARKETProtocol/MARKET.js/issues/14. Due to the size and scope of the testing, we created a new project and repo for the MARKET.js types.

### Description

*Type*: Enhancement

### Current Behavior
There is minimal test coverage.

### Expected Behavior
We need 100% test coverage on the TypeScript ABIs.

### Solution
*Summary*:
[Typechain](https://github.com/Neufund/TypeChain) is being used to generate types and the ABIs from which to generate the types is specified as a glob pattern in the package.json under config.typechain.include which is currently set to: Market*|CollateralToken|OraclizeQueryTest|ERC20|OrderLib

### Definition of Done
- Create tests for the MarketToken ABI

**Comment by ConnorChristie** [comment]
These tests will be implemented in the first PR #1
