### ISSUE TITLE
Move MARKET.js specific types and types that are under heavy modification back to MARKET.js

### ISSUE THREAD

**Issue by pelsasser** [MARKETProtocol/types#26]
### User Story
As a user / dev I hate having to modify two repos and wait on releases!

### Why Is this Needed?

*Summary*: ease the life of our contributors and @MARKETProtocol/core 

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Feature

### Current Behavior
MARKET.js specific types and types under heavy development are in a seperated repo

### Expected Behavior
MARKET.js specific types and types under heavy development should be in the MARKET.js repo for ease of modification.  We could use a submodule, or debate the monorepo approach but for now this is probably an easier path forward.

**Comment by eswarasai** [comment]
@pelsasser -- I have left the `Config.ts` in `types` repo since there might not be heavy changes to the `MarketProtocolConfig` on a day-to-day basis. Let me know if otherwise, I can quickly refactor that too. If not, we're good to close this issue :)

**Comment by pelsasser** [comment]
@eswarasai - I think based on our conversation yesterday, and the fact that the config is MARKET.js specific object we should move it back, at least for the time being.

**Comment by eswarasai** [comment]
@pelsasser -- Done 👍
