### ISSUE TITLE
In Artifact `contract_name` should be renamed to `contractName`.

### ISSUE THREAD

**Issue by perfectmak** [MARKETProtocol/types#32]
The generated truffle ABI json file which is usually imported as an `Artifact` in the other projects creates the contract name field as `contractName`, but in the `Artifact` class [here](https://github.com/MARKETProtocol/types/blob/c773d8d1a1fac94ed35e868156d6a33477d81686/types/Artifact.ts#L2), you would see that the name of the field exported is `contract_name`.

Using the `contract_name` would lead to `undefined`.

### Summary
Rename `contract_name` to `contractName` in the `Artifact` class, so it would match the ABI json files.

**Comment by pelsasser** [comment]
Thanks for the heads up @perfectmak!
